### ISSUE TITLE
Use a specific version of pangolin-assignment

### ISSUE THREAD

**Issue by jpalmer37** [cov-lineages/pangolin-assignment#24]
Hi there,

There might already be a way to manually do this, in which case I would simply request some guidance. I am looking to use a specific version of the pangolin-assignment cache and pangolin-data which is not the absolute latest (with latest being chosen by default). At the time of writing this, v1.11 is the latest and I am looking to use v1.09 (simply a matter of consistency within our network).  Is this possible within the current framework?  

Thanks in advance!

**Comment by AngieHinrichs** [comment]
Hi @jpalmer37 - @kapsakcj maintains docker images for specific version combos, and those are probably the most solid for reproducing results, if docker works for you:  https://hub.docker.com/r/staphb/pangolin/tags?page=1&ordering=last_updated

If docker's not for you, then there are some pangolin command line options that can be used to get an older data model, although the default assumption with pangolin is that latest is best because it incorporates the newest lineages and sometimes fixes for problems in older versions.  I assume you're using UShER analysis mode since the pangolin-assignment cache is available only for UShER at this point.  

You can download the v1.9 pangolin-data UShER tree file like this:
```
curl -kL -o pangolin-data.v1.9.tar.gz https://github.com/cov-lineages/pangolin-data/archive/refs/tags/v1.9.tar.gz
tar xvzf pangolin-data.v1.9.tar.gz
```
Then the UShER tree file will be `pangolin-data-1.9/pangolin_data/data/lineageTree.pb`.

You can download an analogous tar file from github for pangolin-assignment, but it won't work because that repository is using git-lfs because the assignment cache is a large file, and although the tar file contains a file `pangolin-assignment-1.9/pangolin_assignment/usher_assignments.cache.csv.gz`, it is actually just some ASCII text with a reference to the real data.  So instead, we have an alternate location:
```
curl -kL -O https://hgdownload.gi.ucsc.edu/goldenPath/wuhCor1/pangolin-assignment/pangolin-assignment-v1.9.tar.gz
tar xvf pangolin-assignment-v1.9.tar.gz
```
Then the assignment cache file will be `pangolin-assignment-v1.9/pangolin_assignment/usher_assignments.cache.csv.gz`.  Now you can tell pangolin to use those specific files like this:
```
pangolin --usher-tree pangolin-data-1.9/pangolin_data/data/lineageTree.pb \
    --assignment-cache pangolin-assignment-v1.9/pangolin_assignment/usher_assignments.cache.csv.gz \
    my.fa
```

That only works for UShER mode, but there's another method that should work for pangoLEARN as well.  After running the curl and tar commands from above, do this:
```
mkdir pangolin-datadir-v1.9
mv pangolin-data-1.9 pangolin-assignment-v1.9 pangolin-datadir-v1.9/

pangolin --use-old-datadir --datadir pangolin-datadir-v1.9 my.fa
# or
pangolin --use-old-datadir --datadir pangolin-datadir-v1.9 --analysis-mode pangolearn my.fa
```
The `--use-old-datadir` option was added to pangolin fairly recently -- without `--use-old-datadir`, pangolin ignores the contents of datadir if they are older than the most recent installed version.
